<a href="https://colab.research.google.com/github/VilasiniRamamoorthy/Mini_Project1/blob/main/TMDB_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TMDB Project Data Cleaning**

In [ ]:
#importing pandas
import pandas as pd

In [ ]:
#reading movies.csv file
movies_df = pd.read_csv('movies.csv')

In [ ]:
#movies.csv dataframe
movies_df

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
0,157336,Interstellar,en,2014-11-05,169,1.650000e+08,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...
1,27205,Inception,en,2010-07-15,148,1.600000e+08,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es..."
2,24428,The Avengers,en,2012-04-25,143,2.200000e+08,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...
3,155,The Dark Knight,en,2008-07-16,152,1.850000e+08,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...
4,19995,Avatar,en,2009-12-16,162,2.370000e+08,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di..."
...,...,...,...,...,...,...,...,...,...,...,...,...
2504,98,Gladiator,en,2000-05-04,155,1.030000e+08,4.655162e+08,38.9610,8.230,21184,Released,"After the death of Emperor Marcus Aurelius, hi..."
2505,1368167,Date Night,en,1995-04-08,88,9.321480e+07,8.759568e+07,8.2930,7.000,1051,Released,Phil and Claire Foster fear that their mild-ma...
2506,1368168,Transformers,en,1987-06-27,144,1.100988e+08,2.747467e+08,6.5902,7.900,4215,Released,Young teenager Sam Witwicky becomes involved i...
2507,1368169,The SpongeBob Movie: Sponge Out of Water,en,2000-01-28,93,3.928488e+07,5.706575e+08,11.3857,7.100,475,Released,Evil pirate Burger Beard is in search of the f...
2508,1368170,Fargo,en,2011-03-08,98,5.425747e+06,4.584468e+07,11.2271,7.900,2514,Released,"Jerry, a small-town Minnesota car salesman is ..."

In [ ]:
#Viewing the dataframe details
movies_df.describe()

,movie_id,runtime,budget,revenue,popularity,vote_average,vote_count
count,2.509000e+03,2509.000000,2.509000e+03,2.509000e+03,2509.000000,2509.000000,2509.000000
mean,1.848254e+05,114.420885,5.863972e+07,2.141241e+08,13.691851,6.941640,6194.598246
std,2.571634e+05,21.412944,6.232276e+07,2.716873e+08,18.096247,0.711199,4963.789824
min,5.000000e+00,45.000000,0.000000e+00,0.000000e+00,0.017000,2.945000,475.000000
25%,4.935000e+03,99.000000,1.450000e+07,4.738629e+07,7.449900,6.437000,3026.000000
50%,3.953800e+04,111.000000,3.800000e+07,1.279000e+08,10.393400,6.949000,4358.000000
75%,3.304590e+05,126.000000,8.250000e+07,2.713333e+08,14.863900,7.448000,7261.000000
max,1.368170e+06,242.000000,6.588000e+08,2.923706e+09,438.475700,8.727000,40566.000000

In [ ]:
#movies.csv dataframe record datatype
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movie_id           2509 non-null   int64
 1   title              2509 non-null   object
 2   original_language  2509 non-null   object
 3   release_date       2509 non-null   object
 4   runtime            2509 non-null   int64
 5   budget             2509 non-null   float64
 6   revenue            2509 non-null   float64
 7   popularity         2509 non-null   float64
 8   vote_average       2509 non-null   float64
 9   vote_count         2509 non-null   int64
 10  status             2509 non-null   object
 11  overview           2509 non-null   object
dtypes: float64(4), int64(3), object(5)
memory usage: 235.3+ KB

In [ ]:
#dataframe data top few rows
movies_df.head()

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
0,157336,Interstellar,en,2014-11-05,169,165000000.0,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...
1,27205,Inception,en,2010-07-15,148,160000000.0,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es..."
2,24428,The Avengers,en,2012-04-25,143,220000000.0,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...
3,155,The Dark Knight,en,2008-07-16,152,185000000.0,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...
4,19995,Avatar,en,2009-12-16,162,237000000.0,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di..."

In [ ]:
#dataframe count
movies_df.count()

movie_id             2509
title                2509
original_language    2509
release_date         2509
runtime              2509
budget               2509
revenue              2509
popularity           2509
vote_average         2509
vote_count           2509
status               2509
overview             2509
dtype: int64

In [ ]:
#dataframe row return
movies_df.shape[0]

2509

In [ ]:
#dropping duplicate rows
movies_df.drop_duplicates()

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
0,157336,Interstellar,en,2014-11-05,169,1.650000e+08,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...
1,27205,Inception,en,2010-07-15,148,1.600000e+08,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es..."
2,24428,The Avengers,en,2012-04-25,143,2.200000e+08,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...
3,155,The Dark Knight,en,2008-07-16,152,1.850000e+08,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...
4,19995,Avatar,en,2009-12-16,162,2.370000e+08,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di..."
...,...,...,...,...,...,...,...,...,...,...,...,...
2498,19901,Daybreakers,en,2010-01-06,98,2.000000e+07,5.141719e+07,6.5762,6.285,2223,Released,"In the year 2019, a plague has transformed alm..."
2505,1368167,Date Night,en,1995-04-08,88,9.321480e+07,8.759568e+07,8.2930,7.000,1051,Released,Phil and Claire Foster fear that their mild-ma...
2506,1368168,Transformers,en,1987-06-27,144,1.100988e+08,2.747467e+08,6.5902,7.900,4215,Released,Young teenager Sam Witwicky becomes involved i...
2507,1368169,The SpongeBob Movie: Sponge Out of Water,en,2000-01-28,93,3.928488e+07,5.706575e+08,11.3857,7.100,475,Released,Evil pirate Burger Beard is in search of the f...
2508,1368170,Fargo,en,2011-03-08,98,5.425747e+06,4.584468e+07,11.2271,7.900,2514,Released,"Jerry, a small-town Minnesota car salesman is ..."

In [ ]:
movies_df.count()

movie_id             2509
title                2509
original_language    2509
release_date         2509
runtime              2509
budget               2509
revenue              2509
popularity           2509
vote_average         2509
vote_count           2509
status               2509
overview             2509
dtype: int64

In [ ]:
%pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3

In [ ]:
%pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (2.1.6)
Requirement already satisfied: pymysql in /usr/local/lib/python3.13/dist-packages (1.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
#Cleaned data loaded to cleaned_movies.csv
import pandas as pd

# Load the CSV file
df = pd.read_csv("movies.csv")

# Replace zero budget values with the mean of non-zero budget values
budget_mean = df.loc[df["budget"] != 0, "budget"].mean()
df.loc[df["budget"] == 0, "budget"] = budget_mean

# Replace zero revenue values with the mean of non-zero revenue values
revenue_mean = df.loc[df["revenue"] != 0, "revenue"].mean()
df.loc[df["revenue"] == 0, "revenue"] = revenue_mean

# Check the results
print("Budget mean:", budget_mean)
print("Revenue mean:", revenue_mean)

print("Remaining zero budgets:", (df["budget"] == 0).sum())
print("Remaining zero revenues:", (df["revenue"] == 0).sum())

# Save the cleaned data
df.to_csv("movies_cleaned.csv", index=False)

In [ ]:
#Creating cleaned data into TiDB database as cleaned_movies record
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 1: Load your CSV
df = pd.read_csv("movies.csv")

# Replace zero budget values with the mean of non-zero budget values
budget_mean = df.loc[df["budget"] != 0, "budget"].mean()
df.loc[df["budget"] == 0, "budget"] = budget_mean

# Replace zero revenue values with the mean of non-zero revenue values
revenue_mean = df.loc[df["revenue"] != 0, "revenue"].mean()
df.loc[df["revenue"] == 0, "revenue"] = revenue_mean

# Step 2: Check the cleaned data
print(df.head())
print(df.isnull().sum())

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

# Step 5: Upload DataFrame to SQL
df.to_sql(
    name="cleaned_movies",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=1000
)

print("Data uploaded successfully!")

# Step 6: Verify the uploaded records
with engine.connect() as conn:
    result = conn.execute(
        text("SELECT COUNT(*) FROM cleaned_movies")
    )
    print("Total rows uploaded:", result.scalar())

engine.dispose()

   movie_id            title original_language release_date  runtime  \
0    157336     Interstellar                en   2014-11-05      169
1     27205        Inception                en   2010-07-15      148
2     24428     The Avengers                en   2012-04-25      143
3       155  The Dark Knight                en   2008-07-16      152
4     19995           Avatar                en   2009-12-16      162

        budget       revenue  popularity  vote_average  vote_count    status  \
0  165000000.0  7.466067e+08     73.0452         8.484       40566  Released
1  160000000.0  8.390306e+08     55.8497         8.400       39727  Released
2  220000000.0  1.518816e+09     72.2515         8.062       38993  Released
3  185000000.0  1.004558e+09     60.5510         8.534       36255  Released
4  237000000.0  2.923706e+09     48.1996         7.610       34348  Released

                                            overview
0  The adventures of a group of explorers who mak...
1  Cobb, a skilled thief who commits corporate es...
2  When an unexpected enemy emerges and threatens...
3  Batman raises the stakes in his war on crime. ...
4  In the 22nd century, a paraplegic Marine is di...
movie_id             0
title                0
original_language    0
release_date         0
runtime              0
budget               0
revenue              0
popularity           0
vote_average         0
vote_count           0
status               0
overview             0
dtype: int64
Data uploaded successfully!
Total rows uploaded: 2509

In [ ]:
#Reading 2nd file movie_keywords.csv to dataframe
movie_keywords_df = pd.read_csv('movie_keywords.csv')

In [ ]:
#Viewing movie_keywords dataframe
movie_keywords_df

       movie_id  keyword_id                    keyword_name
0        157336        1612                      spacecraft
1        157336        4776               race against time
2        157336         310  artificial intelligence (a.i.)
3        157336        1432                            nasa
4        157336        1521                       time warp
...         ...         ...                             ...
41696      1271      329753                     epic heroes
41697     10483         378                          prison
41698       111         701                            cuba
41699    339397       10048                 unrequited love
41700      7446      167477                       land mine

[41701 rows x 3 columns]

In [ ]:
#Data type of the movie_keywords dataframe
movie_keywords_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41701 entries, 0 to 41700
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      41701 non-null  int64
 1   keyword_id    41701 non-null  int64
 2   keyword_name  41701 non-null  object
dtypes: int64(2), object(1)
memory usage: 977.5+ KB

In [ ]:
#Droping duplicate rows
movie_keywords_df.drop_duplicates()

       movie_id  keyword_id                    keyword_name
0        157336        1612                      spacecraft
1        157336        4776               race against time
2        157336         310  artificial intelligence (a.i.)
3        157336        1432                            nasa
4        157336        1521                       time warp
...         ...         ...                             ...
41676     19901       34079                           death
41677     19901      160153                            dead
41678     19901      232469                    urban gothic
41679     19901      243150                   brutal deaths
41680     19901      325824                         hopeful

[41681 rows x 3 columns]

In [ ]:
#Count of the dataframe
movie_keywords_df.count()

movie_id        41701
keyword_id      41701
keyword_name    41701
dtype: int64

In [ ]:
#Ensuring null check and checking the count of the null
movie_keywords_df.isnull().sum()

movie_id        0
keyword_id      0
keyword_name    0
dtype: int64

In [ ]:
#Checking unique check (just checking this is not needed)
movie_keywords_df['movie_id'].unique()

array([157336,  27205,  24428, ...,  13680,   7461,  19901])

In [ ]:
#Dropping duplicates and getting returned rows
movie_keywords_df.drop_duplicates().shape[0]

41681

In [ ]:
#Verifying if there any more duplicates after drop (just ensuring after drop)
movie_keywords_df.duplicated().sum()

np.int64(20)

In [ ]:
#Creating cleaned_movie_keywords after cleaning dataframe to TiDB database
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 1: Load your CSV
df = pd.read_csv("movie_keywords.csv")

# Step 2: Check the cleaned data
print(df.head())
print(df.isnull().sum())
print(df.drop_duplicates().sum())

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

# Step 5: Upload DataFrame to SQL
df.to_sql(
    name="cleaned_movie_keywords",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=1000
)

print("Data uploaded successfully!")

# Step 6: Verify the uploaded records
with engine.connect() as conn:
    result = conn.execute(
        text("SELECT COUNT(*) FROM cleaned_movie_keywords")
    )
    print("Total rows uploaded:", result.scalar())

engine.dispose()

   movie_id  keyword_id                    keyword_name
0    157336        1612                      spacecraft
1    157336        4776               race against time
2    157336         310  artificial intelligence (a.i.)
3    157336        1432                            nasa
4    157336        1521                       time warp
movie_id        0
keyword_id      0
keyword_name    0
dtype: int64
movie_id                                               7096982345
keyword_id                                             4391737101
keyword_name    spacecraftrace against timeartificial intellig...
dtype: object
Data uploaded successfully!
Total rows uploaded: 41701

In [ ]:
#Reading 3rd file movie_generes csv
movie_generes_df = pd.read_csv('movie_genres.csv')

In [ ]:
#Listing the datatype of the record
movie_generes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6888 entries, 0 to 6887
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  6888 non-null   int64
 1   genre_id  6888 non-null   int64
dtypes: int64(2)
memory usage: 107.8 KB

In [ ]:
#Checking the count of the dataframe
movie_generes_df.count()

movie_id    6888
genre_id    6888
dtype: int64

In [ ]:
#Dropping duplicates in movie_generes and checking dropped duplicates
movie_generes_df.drop_duplicates().sum()

movie_id    1272368327
genre_id      11571787
dtype: int64

In [ ]:
#Verifying the null and checking the null row count
movie_generes_df.isnull().sum()

movie_id    0
genre_id    0
dtype: int64

In [ ]:
#Creating record after cleaned dataframe for movie_genres
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 1: Load your CSV
df = pd.read_csv("movie_genres.csv")

# Step 2: Check the cleaned data
print(df.head())
print(df.isnull().sum())
print(df.drop_duplicates().sum())

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

# Step 5: Upload DataFrame to SQL
df.to_sql(
    name="cleaned_movie_genres",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=1000
)

print("Data uploaded successfully!")

# Step 6: Verify the uploaded records
with engine.connect() as conn:
    result = conn.execute(
        text("SELECT COUNT(*) FROM cleaned_movie_genres")
    )
    print("Total rows uploaded:", result.scalar())

engine.dispose()

   movie_id  genre_id
0    157336        12
1    157336        18
2    157336       878
3     27205        28
4     27205       878
movie_id    0
genre_id    0
dtype: int64
movie_id    1272368327
genre_id      11571787
dtype: int64
Data uploaded successfully!
Total rows uploaded: 6888

In [ ]:
#Reading genres.csv into dataframe genres_df
genres_df = pd.read_csv('genres.csv')

In [ ]:
#After dataframe verifying the datatype
genres_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   genre_id    19 non-null     int64
 1   genre_name  19 non-null     object
dtypes: int64(1), object(1)
memory usage: 436.0+ bytes

In [ ]:
#Reading crew file to crew_df dataframe
crew_df = pd.read_csv('crew.csv')

In [ ]:
#Verifying the crew dataframe datatype
crew_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7297 entries, 0 to 7296
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   crew_row_id  7297 non-null   int64
 1   movie_id     7297 non-null   int64
 2   person_id    7297 non-null   int64
 3   person_name  7297 non-null   object
 4   job          7297 non-null   object
 5   department   7297 non-null   object
dtypes: int64(3), object(3)
memory usage: 342.2+ KB

In [ ]:
#Checking the null values
crew_df.isnull().sum()

crew_row_id    0
movie_id       0
person_id      0
person_name    0
job            0
department     0
dtype: int64

In [ ]:
#Checking the crew datafram duplicate
crew_df.duplicated().sum()

np.int64(8)

In [ ]:
#Dropping the duplicates and returning the counts
crew_df.drop_duplicates().shape[0]

7289

In [ ]:
#Creating genres and crew records together in db
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 1: Load the CSV files
genres_df = pd.read_csv("genres.csv")
crew_df = pd.read_csv("crew.csv")

# Step 2: Inspect and check the data
for name, df in [("genres", genres_df), ("crew", crew_df)]:
    print(f"\n--- {name.upper()} DATA ---")
    print(df.head())
    print("\nNull values:")
    print(df.isnull().sum())
    print("\nTotal null values:", df.isnull().sum().sum())
    print("\nDuplicate rows:", df.duplicated().sum())
    print("Unique rows:", df.drop_duplicates().shape[0])

# Step 3: Remove duplicate rows (if appropriate)
genres_df = genres_df.drop_duplicates()
crew_df = crew_df.drop_duplicates()

# Step 4: TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 5: Create the database connection
connection_url = (
    f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)

engine = create_engine(connection_url, pool_recycle=300)

# Step 6: Upload both DataFrames into separate tables
genres_df.to_sql(
    name="cleaned_genres",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=1000
)

crew_df.to_sql(
    name="cleaned_crew",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=1000
)

print("\nBoth tables uploaded successfully!")

# Step 7: Verify the uploaded row counts
with engine.connect() as conn:
    for table in ["cleaned_genres", "cleaned_crew"]:
        result = conn.execute(
            text(f"SELECT COUNT(*) FROM `{table}`")
        )
        print(f"{table}: {result.scalar()} rows uploaded")

engine.dispose()

--- GENRES DATA ---
   genre_id genre_name
0        28     Action
1        12  Adventure
2        16  Animation
3        35     Comedy
4        80      Crime

Null values:
genre_id      0
genre_name    0
dtype: int64

Total null values: 0

Duplicate rows: 0
Unique rows: 19

--- CREW DATA ---
   crew_row_id  movie_id  person_id        person_name       job department
0            1    157336        527     Jonathan Nolan    Writer    Writing
1            2    157336        525  Christopher Nolan    Writer    Writing
2            3    157336        525  Christopher Nolan  Director  Directing
3            4     27205        525  Christopher Nolan    Writer    Writing
4            5     27205        525  Christopher Nolan  Director  Directing

Null values:
crew_row_id    0
movie_id       0
person_id      0
person_name    0
job            0
department     0
dtype: int64

Total null values: 0

Duplicate rows: 8
Unique rows: 7289

Both tables uploaded successfully!
cleaned_genres: 19 rows uploaded
cleaned_crew: 7289 rows uploaded

In [ ]:
#Reading cast.csv, dropping duplicates and creating records in db
import pandas as pd
from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

# Step 1: Load your CSV
df = pd.read_csv("cast.csv")

# Step 2: Check the cleaned data
print(df.head())
print(df.isnull().sum())
print("Unique rows:", df.drop_duplicates().shape[0])

# Step 3: Enter your TiDB connection details
host = "gateway01.ap-northeast-1.prod.aws.tidbcloud.com"
port = 4000
user = "3k5gspKEptkYxvs.root"
password = "uJVYvVceTGGGT00O"
database = "tmdb_proj_vilasini"

# Step 4: Create the database connection
connection_url = (f"mysql+pymysql://{user}:{password}"
    f"@{host}:{port}/{database}"
    "?ssl_verify_cert=true&ssl_verify_identity=true"
)
engine = create_engine(connection_url, pool_recycle=300)

# Step 5: Upload DataFrame to SQL
df.to_sql(
    name="cleaned_cast",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=1000
)

print("Data uploaded successfully!")

# Step 6: Verify the uploaded records
with engine.connect() as conn:
    result = conn.execute(
        text("SELECT COUNT(*) FROM cleaned_cast")
    )
    print("Total rows uploaded:", result.scalar())

engine.dispose()

   cast_row_id  movie_id  person_id           actor_name   character_name  \
0            1    157336      10297  Matthew McConaughey           Cooper
1            2    157336       1813        Anne Hathaway            Brand
2            3    157336       3895        Michael Caine  Professor Brand
3            4    157336      83002     Jessica Chastain            Murph
4            5    157336       1893        Casey Affleck              Tom

   cast_order
0           0
1           1
2           2
3           3
4           4
cast_row_id        0
movie_id           0
person_id          0
actor_name         0
character_name    11
cast_order         0
dtype: int64
Unique rows: 24902
Data uploaded successfully!
Total rows uploaded: 24917